### ISSUE TITLE
Type conversion in tags API specification

### ISSUE THREAD

**Issue by ms32035** [firefly-iii/api-docs-generator#3]
The following part in `tags` api
```
      - in: query
        name: include
        style: form
        explode: false
        description: Comma-separated list of other items that are related to the tag and must be included as well.
        required: false
        schema:
          type: array
          items:
            type: string
            minItems: 1
            enum:
              - user
```
Causes client code generator to fail with errors like:
```
Exception: io.swagger.v3.oas.models.media.StringSchema cannot be cast to io.swagger.v3.oas.models.media.ArraySchema
        at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1039)
        at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:930)
        at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:511)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:891)
        at org.openapitools.codegen.cmd.Generate.run(Generate.java:355)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:62)
Caused by: java.lang.ClassCastException: io.swagger.v3.oas.models.media.StringSchema cannot be cast to io.swagger.v3.oas.models.media.ArraySchema
        at org.openapitools.codegen.languages.PythonClientCodegen.getTypeDeclaration(PythonClientCodegen.java:406)
        at org.openapitools.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:2006)
        at org.openapitools.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:2832)
        at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:2475)
        at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1007)
```
This is for every generated languague

**Comment by JC5** [comment]
OK. I have no idea what to do about that though. :grin:

**Comment by ms32035** [comment]
Well. I just removed the bit and successfully generated a client :)

**Comment by JC5** [comment]
Which bit exactly?

**Comment by ms32035** [comment]
The whole block, but I guess the issue is some conflict between type `string` and enum `user`. Probably a relation type would be a correct fix. Will play a bit more later this week

**Comment by JC5** [comment]
Thanks for the hints. I’ll try it as well. Are you using the Swagger code generators?

**Comment by ms32035** [comment]
https://github.com/OpenAPITools/openapi-generator
Release 3.3.4

**Comment by ms32035** [comment]
Not sure how that parameter is supposed to work, but my gut feeling is that it should actually be submitted as as string not array, something like:
```
        schema:
          type: string
          example: 1, 3, 2
```
which works correctly

**Comment by JC5** [comment]
Ah, I see it now. Those `include` parameters are deprecated anyway. I've removed it. Thanks for pointing it out! :+1:
